version: '3.8'

services:
  postgres:
    container_name: postgresdb
    build: ./docker/postgres
    image: postgresdb
    ports:
      - '127.0.0.1:5432:5432'
    networks:
      dev:
        aliases:
          - ${DB_ALIAS}
    env_file:
      - .env
    volumes:
      - ./docker-data/postgres/data:/var/lib/postresql/data
    environment:
      PGDATA: /var/lib/postgresql/dat
    restart: always

  nodejs:
    container_name: nodejs
    build: ./docker/nodejs
    image: nodejs
    networks:
      dev:
        aliases:
          - ${APP_ALIAS}
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
     - 3000:3000
    command: yarn start:dev
    restart: always
networks:
  dev:
    external:
      name: dev